// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBLWm1Wo-XBjXh8AThy_jq499GnBKRpgk',
    appId: '1:463710307490:web:b8943c07bf5e2eace8c3fb',
    messagingSenderId: '463710307490',
    projectId: 'grad-911d2',
    authDomain: 'grad-911d2.firebaseapp.com',
    databaseURL: 'https://grad-911d2-default-rtdb.firebaseio.com',
    storageBucket: 'grad-911d2.firebasestorage.app',
    measurementId: 'G-8LB9V4CZPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFFvyJbi8keuvc3j_WPNb2ty3NxO5bmP0',
    appId: '1:463710307490:android:1f1ee8f6c7115eece8c3fb',
    messagingSenderId: '463710307490',
    projectId: 'grad-911d2',
    databaseURL: 'https://grad-911d2-default-rtdb.firebaseio.com',
    storageBucket: 'grad-911d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXgS52Xx-gtXrCpWdDgU6yVa3SV5q9wE',
    appId: '1:463710307490:ios:2e4e62a016a3900ee8c3fb',
    messagingSenderId: '463710307490',
    projectId: 'grad-911d2',
    databaseURL: 'https://grad-911d2-default-rtdb.firebaseio.com',
    storageBucket: 'grad-911d2.firebasestorage.app',
    iosBundleId: 'com.example.jdnyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrXgS52Xx-gtXrCpWdDgU6yVa3SV5q9wE',
    appId: '1:463710307490:ios:2e4e62a016a3900ee8c3fb',
    messagingSenderId: '463710307490',
    projectId: 'grad-911d2',
    databaseURL: 'https://grad-911d2-default-rtdb.firebaseio.com',
    storageBucket: 'grad-911d2.firebasestorage.app',
    iosBundleId: 'com.example.jdnyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBLWm1Wo-XBjXh8AThy_jq499GnBKRpgk',
    appId: '1:463710307490:web:ba25cb6337d70f0fe8c3fb',
    messagingSenderId: '463710307490',
    projectId: 'grad-911d2',
    authDomain: 'grad-911d2.firebaseapp.com',
    databaseURL: 'https://grad-911d2-default-rtdb.firebaseio.com',
    storageBucket: 'grad-911d2.firebasestorage.app',
    measurementId: 'G-MM2V5W23C6',
  );

}